export const GET_PRODUCTS = '/api/products';
export const GET_PRODUCTS_ID = (id) => `/api/products/${id}`;
export const POST_LOGIN = '/authentication/login';
export const POST_REGISTER = '/authentication/register';
export const POST_BANNER = '/api/banners';
export const POST_BESTSELLER = '/api/products/bestseller';
export const GET_PRODUCT_COMMENT_BY_ID = (id) => `/api/comments/product/${id}`;
export const POST_COMMENT = '/api/comments';
export const POST_ORDER = '/api/orders';
export const POST_ORDER_USER = '/api/orders/user';
export const POST_GET_USER_BY_PHONENUMBER = '/api/users/getUserByPhoneNumber';
export const POST_CREATE_BILL = '/api/bill/createBill';
export const POST_DELETE_CART = '/api/orders/delete';
export const POST_GET_LIST_BILL_BY_DATE = '/api/bill/getListBillByDate';
export const POST_UPDATE_BILL_STATUS = '/api/bill/updateBillStatus';
export const POST_GET_LIST_BILL_BY_USERID = '/api/bill/getListBillByUserId';
